/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        primary: 'var(--color-primary)',
        'primary-light': 'var(--color-primary-light)',
        danger: 'var(--color-danger)',
        warning: 'var(--color-warning)',
        info: 'var(--color-info)',
        success: 'var(--color-success)',
        critical: 'var(--color-critical)',
        'critical-dark': 'var(--color-critical-dark)',
        gray: {
          25: 'var(--color-gray-soft-25)',
          50: 'var(--color-gray-soft-50)',
          400: 'var(--color-gray-soft-400)',
          500: 'var(--color-gray-soft-500)',
          700: 'var(--color-gray-soft-700)',
        },
      },
      spacing: {
        xs: 'var(--spacing-xs)',
        sm: 'var(--spacing-sm)',
        md: 'var(--spacing-md)',
        lg: 'var(--spacing-lg)',
        xl: 'var(--spacing-xl)',
        '2xl': 'var(--spacing-2xl)',
        '3xl': 'var(--spacing-3xl)',
        '4xl': 'var(--spacing-4xl)',
        '5xl': 'var(--spacing-5xl)',
        '10px': 'var(--spacing-10px)',
        '13px': 'var(--spacing-13px)',
        '18px': 'var(--spacing-18px)',
        '20px': 'var(--spacing-20px)',
        '30px': 'var(--spacing-30px)',
        '50px': 'var(--spacing-50px)',
        '53px': 'var(--spacing-53px)',
        '120px': 'var(--spacing-120px)',
        '250px': 'var(--spacing-250px)',
        '260px': 'var(--spacing-260px)',
        '385px': 'var(--spacing-385px)',
        '400px': 'var(--spacing-400px)',
        '500px': 'var(--spacing-500px)',
        '800px': 'var(--spacing-800px)',
        '860px': 'var(--spacing-860px)',
        '1400px': 'var(--spacing-1400px)',
      },
      borderRadius: {
        xs: 'var(--radius-xs)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        full: 'var(--radius-full)',
      },
      fontSize: {
        '9-45px': 'var(--font-size-9-45px)',
        xs: 'var(--font-size-xs)',
        '12-15px': 'var(--font-size-12-15px)',
        xss: 'var(--font-size-xss)',
        sm: 'var(--font-size-sm)',
        "base-md": 'var(--font-size-base-md)',
        base: 'var(--font-size-base)',
        lg: 'var(--font-size-lg)',
        xl: 'var(--font-size-xl)',
        '2xl': 'var(--font-size-2xl)',
      },
      letterSpacing: {
        '1': 'var(--letter-spacing-1-percent)',
        '400': 'var(--letter-spacing-400)',
      },
      boxShadow: {
        tooltip: 'var(--shadow-tooltip)',
        'card-sm': 'var(--shadow-card-sm)',
        'card-md': 'var(--shadow-card-md)',
        overlay: 'var(--shadow-overlay)',
        button: 'var(--shadow-button)',
        node: 'var(--shadow-node)',
        'node-hover': 'var(--shadow-node-hover)',
        badge: 'var(--shadow-badge)',
      },
      lineHeight: {
        '10-13px': 'var(--line-height-10-13px)',
        '13-5px': 'var(--line-height-13-5px)',
        sm: 'var(--line-height-sm)',
        md: 'var(--line-height-md)',
        base: 'var(--line-height-base)',
        lg: 'var(--line-height-lg)',
      },
      width: {
        sidebar: 'var(--sidebar-width)',
        'sidebar-collapsed': 'var(--sidebar-collapsed-width)',
        'sidebar-collapsed-lg': 'var(--sidebar-collapsed-width-lg)',
        'sidebar-mobile': 'var(--sidebar-width-mobile)',
        'sidebar-mobile-min': 'var(--sidebar-min-width-mobile)',
        'asset-list': 'var(--asset-list-width)',
        'risk-summary': 'var(--risk-summary-width)',
        'right-column': 'var(--right-column-width)',
        'tooltip-max': 'var(--tooltip-max-width)',
      },
      height: {
        graph: 'var(--graph-height)',
        'graph-mobile': 'var(--graph-height-mobile)',
        'graph-container': 'var(--graph-container-height)',
      },
      fontFamily: {
        sans: [
          '"Public Sans"',
          'ui-sans-serif',
          'system-ui',
          'sans-serif',
        ],
      }
    },
  },
}